---
name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  gh_tagged_release:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2.3.4'
      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn build'
      - run: 'yarn test'

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            lib/
        id: 'automatic_releases'
